### ISSUE TITLE
Encountered an error (TypeError: First argument must be a string)

### ISSUE THREAD

**Issue by SoftCreatorRAD** [jarvis394/habra#121]
### Describe the problem:
Got an error message at `/news/p/9`:
```javascript
TypeError: First argument must be a string

    at t (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:452626)
    at Io (https://habra.vercel.app/static/js/main.78454288.chunk.js:1:171050)
    at ul
    at https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:2062015
    at https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:2011678
    at div
    at Rr (https://habra.vercel.app/static/js/main.78454288.chunk.js:1:77307)
    at Ss (https://habra.vercel.app/static/js/main.78454288.chunk.js:1:256841)
    at t (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:9720)
    at t (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:11768)
    at gu (https://habra.vercel.app/static/js/main.78454288.chunk.js:1:365449)
    at div
    at div
    at c (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:88157)
    at t (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:2136149)
    at https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:2028790
    at Eh (https://habra.vercel.app/static/js/main.78454288.chunk.js:1:434442)
    at t (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:6323)
    at t (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:23068)
    at u (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:20135)
    at https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:2138254
```

**Comment by SoftCreatorRAD** [comment]
URL: https://habra.vercel.app/news/p/9
Error happens on scrolling down.
